### ISSUE TITLE
请问作业中owner有什么用处？

### ISSUE THREAD

**Issue by WangZhenhuaFirst** [Guigulive/Team-E#7]
@chenyaxun1 第一课的作业中：

function updateEmployee 中

`require(msg.sender == owner)`  有什么意义？

```
function Payroll() {
    owner = msg.sender;
}
```
又有什么意义？

没有owner 这个变量，程序不是一样可以正常执行吗？

**Comment by hezhihua81** [comment]
确保只有合约的创建者（这里一般是老板）才能更新员工信息。否则随便一个人都可以把员工地址改为自己的。
